### ISSUE TITLE
Error when trying to validate sub attribute of null

### ISSUE THREAD

**Issue by javve** [ansman/validate.js#17]
I have a constraint looking like this:
```coffeescript
  'copy.primaryColor':
    format:
      pattern: "^#(?:[0-9a-f]{3}){1,2}$"
      flags: "i"
      message: "must be a valid hex color"
```
The problem is that everything breaks if `copy` is null.
```
TypeError: Cannot use 'in' operator to search for 'primaryColor' in null
  at Function.v.extend.getDeepObjectValue (/Users/javve/Git/confetti/confetti-api/node_modules/validate.js/validate.js:310:18)
  at Function.v.extend.runValidations (/Users/javve/Git/confetti/confetti-api/node_modules/validate.js/validate.js:66:19)
  at Function.v.extend.async (/Users/javve/Git/confetti/confetti-api/node_modules/validate.js/validate.js:129:23)
```

**Comment by ansman** [comment]
Interesting, I'll take a closer look when I'm back from vacation

**Comment by javve** [comment]
:+1: :v:

**Comment by javve** [comment]
WOHO! :heart:
